%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: C:\Users\eucab\Google Drive\Uni\2020 Sem 1\COMP4702\Pracs\Week 4\pima_indians_diabetes.csv
%
% Auto-generated by MATLAB on 18-Mar-2020 17:47:58

%% Setup the Import Options
opts = delimitedTextImportOptions("NumVariables", 9);

% Specify range and delimiter
opts.DataLines = [1, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["X1", "X2", "X3", "X4", "X5", "X6", "X7", "X8", "cat"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "categorical"];
opts = setvaropts(opts, 9, "EmptyFieldRule", "auto");
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
tbl = readtable("C:\Users\eucab\Google Drive\Uni\2020 Sem 1\COMP4702\Pracs\Week 4\pima_indians_diabetes.csv", opts);

%% Convert to output type
X1 = tbl.X1(2:end);
X2 = tbl.X2(2:end);
X3 = tbl.X3(2:end);
X4 = tbl.X4(2:end);
X5 = tbl.X5(2:end);
X6 = tbl.X6(2:end);
X7 = tbl.X7(2:end);
X8 = tbl.X8(2:end);
cat = tbl.cat(2:end);

%% Clear temporary variables
clear opts tbl